version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: e-commerce-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8081/auth
      KEYCLOAK_REALM: myrealm
      KEYCLOAK_CLIENT_ID: my-springboot-backend
      KEYCLOAK_CLIENT_SECRET: your-client-secret
    networks:
      - app-network
    depends_on:
      - db
      - keycloak

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-config.json
    ports:
      - "8081:8080"  # Maps host port 8081 to container port 8080
    networks:
      - app-network
    volumes:
      - ./keycloak-config:/tmp
    command: start-dev  # Override the default command with start-dev

networks:
  app-network:
    driver: bridge
