name: Docker Compose Build

on:
  push:
    branches:
      - '**' # This will trigger the action on all branches

jobs:
  test_docker_compose:
    name: Test Docker Compose Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ghcr.io

    - name: Build and run Docker Compose
      run: |
        docker-compose build --no-cache
        docker-compose up -d

    - name: Stop Docker Compose
      run: docker-compose down --remove-orphans
