name: Docker Compose Build

on:
  push:
    branches:
      - '**' # This will trigger the action on all branches

jobs:
  test_docker_compose:
    name: Test Docker Compose Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up Docker
      uses: docker/setup-docker-action@v2
      with:
        arch: amd64

    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ghcr.io

    - name: Build and run Docker Compose
      run: |
        docker-compose build --no-cache
        docker-compose up -d
 
    - name: Test Backend Service
      run: |
        curl -s http://backend:8080/api/healthcheck | jq -r '.status'
      id: backend_status
 
    - name: Check Backend Service Status
      run: |
        if [ "${{ steps.backend_status.outputs.status }}" != "UP" ]; then
          echo "Backend service is not healthy."
          exit 1
        fi
 
    - name: Stop Docker Compose
      run: docker-compose down --remove-orphans
